// https://via.placeholder.com/300x150
export const MainProjects = [
	{
		id: 4,
		subtitle: 'Halaman web yang dirancang khusus untuk memperkenalkan dan menggambarkan keindahan dan daya tarik Gunung Bromo.',
		title: 'Bromo Leanding Page',
		tech: 'ReactJs, SASS',
		image: '/projects-img/bromo.png',
		year: 2023,
		github: 'https://github.com/tiedsandi/project-landing-page-bromo',
		live: 'https://bromo-landing-page.netlify.app',
	},
	{
		id: 3,
		subtitle: 'Menampilkan movie dan series tv yang sedang tren dan tayang saat ini',
		title: 'D-Watch',
		image: '/projects-img/D-Watch.png',
		year: 2023,
		tech: 'ReactJs, SASS',
		github: 'https://github.com/tiedsandi/project-d-watch',
		live: 'https://d-watch.netlify.app/',
	},
	{
		id: 2,
		subtitle: 'E-commerc yang menjual pakaian dan aksesorisnya',
		title: 'crwncloth',
		image: '/projects-img/crwncloth.png',
		year: 2022,
		tech: ' Reactjs, Redux, Firebase',
		github: 'https://github.com/tiedsandi/project-crwn-clthv2',
		live: 'https://crwn-clothing-shopid.netlify.app',
		video: 'https://www.youtube.com/watch?v=fEMlPa7jI5Q',
	},
	{
		id: 1,
		subtitle: 'final project Binar Academy, kerja sama dengan tim backend dengan Agile',
		title: 'secondhand',
		image: '/projects-img/secondhand.png',
		year: 2022,
		tech: 'ReactJS, Redux Toolkit, MUI, Axios',
		github: 'https://github.com/tiedsandi/project-secondhandBinar',
		live: 'https://secondhand-2022.netlify.app',
		video: 'https://youtu.be/eB3ACmA-Y48',
	},
];
export const SideProjects = [
	{
		id: 'a1',
		subtitle: 'Belajar Fullstack MERN',
		title: 'Blog FullStack MERN',
		image: 'https://placehold.co/500?text=This+is+Image&font=roboto',
		year: 2023,
		tech: 'ReactJs, Redux, Axios, MUI, Node, Express, MongoesDB',
		github: 'https://github.com/tiedsandi/belajar-fullstack-mern',
	},
	{
		id: 'a2',
		subtitle: 'Implementasi penggunaan React-hook-form, buka console untuk melihat hasil input',
		title: 'Checkout Homepage',
		image: 'https://placehold.co/500?text=This+is+Image&font=roboto',
		year: 2023,
		tech: 'Reactjs, Styled-Components, React-hook-form',
		github: 'https://github.com/tiedsandi/checkout-page',
	},
];
// https://placehold.co/500?text=This+is+Image&font=roboto
